---
title: "Confidence Interval k-fold/batching TAR"
output:
  html_notebook: default
date: '2024-01-30'
---

```{r, include=FALSE}
rm(list = ls(all = TRUE))
graphics.off()
wdir = "/Users/LvB/Documents/! Expectile Asymptotics/!code"
setwd(wdir)
```

```{r}
library(VGAM)
library(tidyverse)
library(expectreg)
library(xtable)
library(rootSolve)
```

TAR with normal innovations
```{r}
alpha = 0.5 #parameter of TAR
df_t = 3 #degree of freedom

simnlts = function(n, alpha, thr, sigma, burnin=100) # normal
#simnlts = function(n, alpha, thr, df, burnin=100) # t distribution
{
  # Generate noise
  e = rnorm(n+burnin, 0, sigma) #normal
  #e = rt(n+burnin, df)  #t distribution
  
  # Create space for y
  y = numeric(n+burnin)
  # Generate time series
  for(i in 2:(n+burnin))
  {
    if(y[i-1] <= thr){
      y[i] = alpha*y[i-1] + e[i]
    }
    else{
      y[i] = -alpha*y[i-1] + e[i]
    }
  }
  # Throw away first burnin values
  y = ts(y[-(1:burnin)])
  # Return result
  return(y)
}
```


```{r}
#true value for TAR with normal innovation
eq.sol=function(mu_tau, para)
{
  alpha = para[1]
  tau = para[2]

  density_TAR = function(x){
    f_x = ((2*(1-alpha^2))/pi)^0.5*exp(-(1-alpha^2)*x^2/2)*pnorm(-alpha*x)
    return(f_x)
  }

  inteq_TAR = function(y){
    y*density_TAR(y)
  }

  inteq_TAR_posi = function(y){
    (y-mu_tau)*density_TAR(y)
  }

  (2 * tau - 1)/(1-tau) * integrate(inteq_TAR_posi, mu_tau, Inf)$value + integrate(inteq_TAR, -Inf, Inf)$value - mu_tau
}
time_start = Sys.time()
## true value
expectile_true_vec = rep(NA, length(tau_vec))
for (i in 1:length(tau_vec)) {
  tau = tau_vec[i]
  find.para = multiroot(eq.sol, start = 0.001, para = c(alpha, tau))
  expectile_true = find.para$root
  expectile_true_vec[i] = expectile_true
}
time_end = Sys.time()
time_dif_1 = time_end - time_start
time_dif_1
expectile_true = expectile_true_vec 
expectile_true
```

k-fold method
```{r}
#number of batch: k
#number of replications: Mrep
#sample size: N
fold = function(k,N,Mrep){
  # 0.95 CI
  cv_vec_0.95 = qt(p = 0.05/2, df = c(1:9), lower.tail = FALSE)
  cv = cv_vec_0.95[k-1]
  # 0.99 CI
  # cv_vec_0.99 = qt(p = 0.01/2, df = c(1:9), lower.tail = FALSE)
  # cv = cv_vec_0.99[k-1]
  
  coverage_prob = rep(NA, length(tau_vec))
  ci_low = rep(NA, length(tau_vec))
  ci_high = rep(NA, length(tau_vec))
  for (i in 1:length(tau_vec)) { 
    tau = tau_vec[i]
    ci = matrix(NA, nrow = Mrep, ncol = 2)
    half_width = rep(NA, Mrep)
    nrep = 0
    for (mrep in 1:Mrep) {
      set.seed(2*mrep + 1)
      #simulate process
      series = simnlts(round(N/k)*k, alpha, thr = 0, sigma = 1) #normal innovation
      #series = simnlts(round(N/k)*k, alpha, thr = 0, df = df_t) # t distribution
      
      indx = rep(1:k,each = round(N/k))  
      series_list = split(series,indx)
      expectile_split_list = lapply(series_list, expectile, probs = tau)
      expectile_split = as.vector(unlist(expectile_split_list))
      expectile_mean = mean(expectile_split)
      sd = sqrt(sum((expectile_split-expectile_mean)^2)/(k-1)) 
      lower = expectile_mean - cv*sd/sqrt(k)
      upper = expectile_mean + cv*sd/sqrt(k)
      ci[mrep,] = as.numeric(c(lower, upper))
      half_width[mrep] = cv*sd/sqrt(k)
      nrep = nrep + 1  
    }
    coverage_prob[i] = sum(expectile_true[i] >= ci[,1] & expectile_true[i] <= ci[,2])/Mrep
    ci_low[i] = mean(ci[,1])
    ci_high[i] = mean(ci[,2])
  }
  width = sqrt(N)*(ci_high - ci_low)/2
  results = list()
  results$prob = coverage_prob
  results$width = width
  return(results)
}
```

```{r}
time1 = Sys.time()
k=2
N=100
results = fold(k,N,Mrep=10000)
width = matrix(NA,1,11)
width[1,1]=k
width[1,2]=N
width[1,3:11] = results$width
prob = matrix(NA,1,11)
prob[1,1]=k
prob[1,2]=N
prob[1,3:11] = results$prob

for (N in c(200,500,1000)){
  results = fold(k,N,Mrep=10000)
  width_new = matrix(NA,1,11)
  width_new[1,2]=N
  width_new[1,3:11] = results$width
  width =rbind(width,width_new)
  prob_new = matrix(NA,1,11)
  prob_new[1,2]=N
  prob_new[1,3:11] = results$prob
  prob =rbind(prob,prob_new)
}
```

```{r}
k=3
N=100
results = fold(k,N,Mrep=10000)
width_new = matrix(NA,1,11)
width_new[1,1]=k
width_new[1,2]=N
width_new[1,3:11] = results$width
width =rbind(width,width_new)
prob_new = matrix(NA,1,11)
prob_new[1,1]=k
prob_new[1,2]=N
prob_new[1,3:11] = results$prob
prob =rbind(prob,prob_new)

for (N in c(200,500,1000)){
  results = fold(k,N,Mrep=10000)
  width_new = matrix(NA,1,11)
  width_new[1,2]=N
  width_new[1,3:11] = results$width
  width =rbind(width,width_new)
  prob_new = matrix(NA,1,11)
  prob_new[1,2]=N
  prob_new[1,3:11] = results$prob
  prob =rbind(prob,prob_new)
}
```

```{r}
k=4
N=100
results = fold(k,N,Mrep=10000)
width_new = matrix(NA,1,11)
width_new[1,1]=k
width_new[1,2]=N
width_new[1,3:11] = results$width
width =rbind(width,width_new)
prob_new = matrix(NA,1,11)
prob_new[1,1]=k
prob_new[1,2]=N
prob_new[1,3:11] = results$prob
prob =rbind(prob,prob_new)

for (N in c(200,500,1000)){
  results = fold(k,N,Mrep=10000)
  width_new = matrix(NA,1,11)
  width_new[1,2]=N
  width_new[1,3:11] = results$width
  width =rbind(width,width_new)
  prob_new = matrix(NA,1,11)
  prob_new[1,2]=N
  prob_new[1,3:11] = results$prob
  prob =rbind(prob,prob_new)
}
```

```{r}
k=5
N=100
results = fold(k,N,Mrep=10000)
width_new = matrix(NA,1,11)
width_new[1,1]=k
width_new[1,2]=N
width_new[1,3:11] = results$width
width =rbind(width,width_new)
prob_new = matrix(NA,1,11)
prob_new[1,1]=k
prob_new[1,2]=N
prob_new[1,3:11] = results$prob
prob =rbind(prob,prob_new)

for (N in c(200,500,1000)){
  results = fold(k,N,Mrep=10000)
  width_new = matrix(NA,1,11)
  width_new[1,2]=N
  width_new[1,3:11] = results$width
  width =rbind(width,width_new)
  prob_new = matrix(NA,1,11)
  prob_new[1,2]=N
  prob_new[1,3:11] = results$prob
  prob =rbind(prob,prob_new)
}
```

```{r}
k=6
N=100
results = fold(k,N,Mrep=10000)
width_new = matrix(NA,1,11)
width_new[1,1]=k
width_new[1,2]=N
width_new[1,3:11] = results$width
width =rbind(width,width_new)
prob_new = matrix(NA,1,11)
prob_new[1,1]=k
prob_new[1,2]=N
prob_new[1,3:11] = results$prob
prob =rbind(prob,prob_new)

for (N in c(200,500,1000)){
  results = fold(k,N,Mrep=10000)
  width_new = matrix(NA,1,11)
  width_new[1,2]=N
  width_new[1,3:11] = results$width
  width =rbind(width,width_new)
  prob_new = matrix(NA,1,11)
  prob_new[1,2]=N
  prob_new[1,3:11] = results$prob
  prob =rbind(prob,prob_new)
}
```

```{r}
k=10
N=100
results = fold(k,N,Mrep=10000)
width_new = matrix(NA,1,11)
width_new[1,1]=k
width_new[1,2]=N
width_new[1,3:11] = results$width
width =rbind(width,width_new)
prob_new = matrix(NA,1,11)
prob_new[1,1]=k
prob_new[1,2]=N
prob_new[1,3:11] = results$prob
prob =rbind(prob,prob_new)

for (N in c(200,500,1000)){
  results = fold(k,N,Mrep=10000)
  width_new = matrix(NA,1,11)
  width_new[1,2]=N
  width_new[1,3:11] = results$width
  width =rbind(width,width_new)
  prob_new = matrix(NA,1,11)
  prob_new[1,2]=N
  prob_new[1,3:11] = results$prob
  prob =rbind(prob,prob_new)
}
time2 = Sys.time()
time2-time1
```
Empirical coverage probabilities for TAR with normal innovation
```{r}
colnames(prob) = c("$d$", "$n$", "$\\alpha=0.1$", "0.2", "0.3","0.4","0.5","0.6","0.7","0.8","0.9")
xtable= xtable(prob,digits=c(0,0,0,rep(3,9)))
print(xtable, include.rownames = FALSE,sanitize.text.function = function(x) {x})
```
Halfwidths for TAR with normal innovation
```{r}
colnames(width) = c("$d$", "$n$", "$\\alpha=0.1$", "0.2", "0.3","0.4","0.5","0.6","0.7","0.8","0.9")
xtable= xtable(width,digits=c(0,0,0,rep(3,9)))
print(xtable, include.rownames = FALSE,sanitize.text.function = function(x) {x})
```



